# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

stages:
- stage: "BuildStage"
  jobs:
  - job: "BuildJob"
    pool:
      vmImage: ubuntu-latest

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'container'

- stage: "DeployToDev"
  dependsOn: "BuildStage"
  jobs: 
  - job: "DepoloyToDevContainer"
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MSDN Platforms Subscription (9814abae-0012-4890-8435-67170c5b55fb)'
        appType: 'webApp'
        WebAppName: 'demo-devapp'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- stage: "DeployToQA"
  dependsOn: "DeployToDev"
  jobs: 
  - job: "DepoloyToDevContainer"
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MSDN Platforms Subscription (9814abae-0012-4890-8435-67170c5b55fb)'
        appType: 'webApp'
        WebAppName: 'demo-QAapp'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- stage: "DeployToProd"
  dependsOn: "DeployToQA"
  jobs: 
  - job: "DepoloyToDevContainer"
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'MSDN Platforms Subscription (9814abae-0012-4890-8435-67170c5b55fb)'
        appType: 'webApp'
        WebAppName: 'demo-Prodapp'
        deployToSlotOrASE: true
        ResourceGroupName: 'DevOpsRG-class'
        SlotName: 'staging'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    - task: AzureAppServiceManage@0
      inputs:
        azureSubscription: 'MSDN Platforms Subscription(9814abae-0012-4890-8435-67170c5b55fb)'
        Action: 'Swap Slots'
        WebAppName: 'demo-Prodapp'
        ResourceGroupName: 'DevOpsRG-class'
        SourceSlot: 'staging'
